package com.zl.pojo;

import java.io.Serializable;

/**
 * tableName{T_Area}
 * by is_zhoufeng@163.com 2015-06-26 01:27:20
 */
public class TArea implements Serializable {
    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    private Integer id;

    /**
     * 编码  
     * column{Code},jdbcType{INTEGER}
     */
    private Integer code;

    /**
     * 名称  
     * column{Name},jdbcType{VARCHAR}
     */
    private String name;

    /**
     * 索引  
     * column{idx},jdbcType{VARCHAR}
     */
    private String idx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_Area
     *
     * @mbggenerated Fri Jun 26 01:27:20 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 编码  
     * column{Code},jdbcType{INTEGER}
     */
    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * 名称  
     * column{Name},jdbcType{VARCHAR}
     */
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * 索引  
     * column{idx},jdbcType{VARCHAR}
     */
    public String getIdx() {
        return idx;
    }

    public void setIdx(String idx) {
        this.idx = idx;
    }
}