package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_Brand}
 * by is_zhoufeng@163.com 2015-06-05 23:56:33
 */
public class TBrand implements Serializable {
    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    private Integer id;

    /**
     * 品牌名称  
     * column{BrandName},jdbcType{VARCHAR}
     */
    private String brandName;

    /**
     * 描述  
     * column{Description},jdbcType{VARCHAR}
     */
    private String description;

    /**
     * 属性  
     * column{Attributes},jdbcType{VARCHAR}
     */
    private String attributes;

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    private Date createTime;

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 品牌名称  
     * column{BrandName},jdbcType{VARCHAR}
     */
    public String getBrandName() {
        return brandName;
    }

    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * 描述  
     * column{Description},jdbcType{VARCHAR}
     */
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 属性  
     * column{Attributes},jdbcType{VARCHAR}
     */
    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}