package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_Chat}
 * by is_zhoufeng@163.com 2015-06-05 23:56:33
 */
public class TChat implements Serializable {
    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 消息接收者  
     * column{ToId},jdbcType{BIGINT}
     */
    private Long toId;

    /**
     * 消息发送者  
     * column{FromId},jdbcType{BIGINT}
     */
    private Long fromId;

    /**
     *   
     * column{Message},jdbcType{VARCHAR}
     */
    private String message;

    /**
     * 消息状态：未读、已读等  
     * column{Status},jdbcType{BIT}
     */
    private Boolean status;

    /**
     * 消息类型：文本，表情，视频等  
     * column{Type},jdbcType{INTEGER}
     */
    private Integer type;

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    private Date createTime;

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_Chat
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 消息接收者  
     * column{ToId},jdbcType{BIGINT}
     */
    public Long getToId() {
        return toId;
    }

    public void setToId(Long toId) {
        this.toId = toId;
    }

    /**
     * 消息发送者  
     * column{FromId},jdbcType{BIGINT}
     */
    public Long getFromId() {
        return fromId;
    }

    public void setFromId(Long fromId) {
        this.fromId = fromId;
    }

    /**
     *   
     * column{Message},jdbcType{VARCHAR}
     */
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * 消息状态：未读、已读等  
     * column{Status},jdbcType{BIT}
     */
    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * 消息类型：文本，表情，视频等  
     * column{Type},jdbcType{INTEGER}
     */
    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}