package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_Device_User}
 * by is_zhoufeng@163.com 2015-06-05 23:56:33
 */
public class TDeviceUser implements Serializable {
    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    private Integer id;

    /**
     * 设备Token  
     * column{DeviceToken},jdbcType{VARCHAR}
     */
    private String deviceToken;

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    private Long userId;

    /**
     * 平台  
     * column{PlatForm},jdbcType{VARCHAR}
     */
    private String platForm;

    /**
     * 版本  
     * column{Version},jdbcType{VARCHAR}
     */
    private String version;

    /**
     * AppID  
     * column{AppId},jdbcType{INTEGER}
     */
    private Integer appId;

    /**
     * 创建时间  
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    private Date createTime;

    /**
     * 修改时间  
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 设备Token  
     * column{DeviceToken},jdbcType{VARCHAR}
     */
    public String getDeviceToken() {
        return deviceToken;
    }

    public void setDeviceToken(String deviceToken) {
        this.deviceToken = deviceToken;
    }

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 平台  
     * column{PlatForm},jdbcType{VARCHAR}
     */
    public String getPlatForm() {
        return platForm;
    }

    public void setPlatForm(String platForm) {
        this.platForm = platForm;
    }

    /**
     * 版本  
     * column{Version},jdbcType{VARCHAR}
     */
    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * AppID  
     * column{AppId},jdbcType{INTEGER}
     */
    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * 创建时间  
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * 修改时间  
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}