package com.zl.pojo;

import java.io.Serializable;

/**
 * tableName{T_File}
 * by is_zhoufeng@163.com 2015-06-09 16:41:24
 */
public class TFile implements Serializable {
    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 文件类型[1:图片，2:语音，3:视频]  
     * column{FileType},jdbcType{TINYINT}
     */
    private Byte fileType;

    /**
     * 源文件名  
     * column{FileName},jdbcType{VARCHAR}
     */
    private String fileName;

    /**
     * 文件地址  
     * column{Url},jdbcType{VARCHAR}
     */
    private String url;

    /**
     * 业务类型[1:用户头像,2:动态,3:聊天]  
     * column{BizType},jdbcType{TINYINT}
     */
    private Byte bizType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 文件类型[1:图片，2:语音，3:视频]  
     * column{FileType},jdbcType{TINYINT}
     */
    public Byte getFileType() {
        return fileType;
    }

    public void setFileType(Byte fileType) {
        this.fileType = fileType;
    }

    /**
     * 源文件名  
     * column{FileName},jdbcType{VARCHAR}
     */
    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * 文件地址  
     * column{Url},jdbcType{VARCHAR}
     */
    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * 业务类型[1:用户头像,2:动态,3:聊天]  
     * column{BizType},jdbcType{TINYINT}
     */
    public Byte getBizType() {
        return bizType;
    }

    public void setBizType(Byte bizType) {
        this.bizType = bizType;
    }
}