package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_Invite_Code}
 * by is_zhoufeng@163.com 2015-06-14 16:08:48
 */
public class TInviteCode implements Serializable {
    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    private Integer id;

    /**
     * 邀请码  
     * column{Code},jdbcType{VARCHAR}
     */
    private String code;

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    private Long userId;

    /**
     * 使用次数  
     * column{UsedCount},jdbcType{INTEGER}
     */
    private Integer usedCount;

    /**
     * 有效期开始时间  
     * column{StartTime},jdbcType{DATE}
     */
    private Date startTime;

    /**
     * 有效期结束时间  
     * column{EndTime},jdbcType{DATE}
     */
    private Date endTime;

    /**
     *   
     * column{attribute},jdbcType{VARCHAR}
     */
    private String attribute;

    /**
     * 状态  
     * column{Status},jdbcType{INTEGER}
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_Invite_Code
     *
     * @mbggenerated Sun Jun 14 16:08:48 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 邀请码  
     * column{Code},jdbcType{VARCHAR}
     */
    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 使用次数  
     * column{UsedCount},jdbcType{INTEGER}
     */
    public Integer getUsedCount() {
        return usedCount;
    }

    public void setUsedCount(Integer usedCount) {
        this.usedCount = usedCount;
    }

    /**
     * 有效期开始时间  
     * column{StartTime},jdbcType{DATE}
     */
    public Date getStartTime() {
        return startTime;
    }

    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * 有效期结束时间  
     * column{EndTime},jdbcType{DATE}
     */
    public Date getEndTime() {
        return endTime;
    }

    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     *   
     * column{attribute},jdbcType{VARCHAR}
     */
    public String getAttribute() {
        return attribute;
    }

    public void setAttribute(String attribute) {
        this.attribute = attribute;
    }

    /**
     * 状态  
     * column{Status},jdbcType{INTEGER}
     */
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }
}