package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_User_Profile}
 * by is_zhoufeng@163.com 2015-07-05 15:41:16
 */
public class TUserProfile implements Serializable {
    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    private Long userId;

    /**
     * 公司  
     * column{Company},jdbcType{VARCHAR}
     */
    private String company;

    /**
     * 职位  
     * column{Position},jdbcType{VARCHAR}
     */
    private String position;

    /**
     * 工作开始时间  
     * column{JobStartTime},jdbcType{BIGINT}
     */
    private Long jobStartTime;

    /**
     * 工作结束时间  
     * column{JobEndTime},jdbcType{BIGINT}
     */
    private Long jobEndTime;

    /**
     * 介绍  
     * column{Introduce},jdbcType{VARCHAR}
     */
    private String introduce;

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    private Date createTime;

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    private Date modifyTime;

    /**
     * 状态  
     * column{Status},jdbcType{INTEGER}
     */
    private Integer status;

    /**
     * 描述：Json格式  
     * column{Attributes},jdbcType{VARCHAR}
     */
    private String attributes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_User_Profile
     *
     * @mbggenerated Sun Jul 05 15:41:16 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 公司  
     * column{Company},jdbcType{VARCHAR}
     */
    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * 职位  
     * column{Position},jdbcType{VARCHAR}
     */
    public String getPosition() {
        return position;
    }

    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * 工作开始时间  
     * column{JobStartTime},jdbcType{BIGINT}
     */
    public Long getJobStartTime() {
        return jobStartTime;
    }

    public void setJobStartTime(Long jobStartTime) {
        this.jobStartTime = jobStartTime;
    }

    /**
     * 工作结束时间  
     * column{JobEndTime},jdbcType{BIGINT}
     */
    public Long getJobEndTime() {
        return jobEndTime;
    }

    public void setJobEndTime(Long jobEndTime) {
        this.jobEndTime = jobEndTime;
    }

    /**
     * 介绍  
     * column{Introduce},jdbcType{VARCHAR}
     */
    public String getIntroduce() {
        return introduce;
    }

    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * 状态  
     * column{Status},jdbcType{INTEGER}
     */
    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * 描述：Json格式  
     * column{Attributes},jdbcType{VARCHAR}
     */
    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }
}