package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_User_Info}
 * by is_zhoufeng@163.com 2015-06-28 21:10:14
 */
public class TUserInfo implements Serializable {
    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    private Long userId;

    /**
     * 昵称  
     * column{NickName},jdbcType{VARCHAR}
     */
    private String nickName;

    /**
     * 性别 0：男  1:女  
     * column{Sex},jdbcType{TINYINT}
     */
    private Byte sex;

    /**
     * 手机号码  
     * column{Mobile},jdbcType{VARCHAR}
     */
    private String mobile;

    /**
     * 邮件地址  
     * column{Email},jdbcType{VARCHAR}
     */
    private String email;

    /**
     * 头衔  
     * column{Title},jdbcType{VARCHAR}
     */
    private String title;

    /**
     * 行业编码  
     * column{Industry},jdbcType{INTEGER}
     */
    private Integer industry;

    /**
     * 地区编码  
     * column{Area},jdbcType{INTEGER}
     */
    private Integer area;

    /**
     * 头像  
     * column{FaceImg},jdbcType{VARCHAR}
     */
    private String faceImg;

    /**
     * 背景链接：图片or视频链接  
     * column{Background},jdbcType{VARCHAR}
     */
    private String background;

    /**
     * 二维码  
     * column{QrCode},jdbcType{VARCHAR}
     */
    private String qrCode;

    /**
     * 描述  
     * column{Description},jdbcType{VARCHAR}
     */
    private String description;

    /**
     * 好友数  
     * column{Friends},jdbcType{INTEGER}
     */
    private Integer friends;

    /**
     * 点赞数  
     * column{Praise},jdbcType{INTEGER}
     */
    private Integer praise;

    /**
     * 待扩展信息  
     * column{Attributes},jdbcType{VARCHAR}
     */
    private String attributes;

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    private Date createTime;

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_User_Info
     *
     * @mbggenerated Sun Jun 28 21:10:14 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 昵称  
     * column{NickName},jdbcType{VARCHAR}
     */
    public String getNickName() {
        return nickName;
    }

    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * 性别 0：男  1:女  
     * column{Sex},jdbcType{TINYINT}
     */
    public Byte getSex() {
        return sex;
    }

    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * 手机号码  
     * column{Mobile},jdbcType{VARCHAR}
     */
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * 邮件地址  
     * column{Email},jdbcType{VARCHAR}
     */
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 头衔  
     * column{Title},jdbcType{VARCHAR}
     */
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * 行业编码  
     * column{Industry},jdbcType{INTEGER}
     */
    public Integer getIndustry() {
        return industry;
    }

    public void setIndustry(Integer industry) {
        this.industry = industry;
    }

    /**
     * 地区编码  
     * column{Area},jdbcType{INTEGER}
     */
    public Integer getArea() {
        return area;
    }

    public void setArea(Integer area) {
        this.area = area;
    }

    /**
     * 头像  
     * column{FaceImg},jdbcType{VARCHAR}
     */
    public String getFaceImg() {
        return faceImg;
    }

    public void setFaceImg(String faceImg) {
        this.faceImg = faceImg;
    }

    /**
     * 背景链接：图片or视频链接  
     * column{Background},jdbcType{VARCHAR}
     */
    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }

    /**
     * 二维码  
     * column{QrCode},jdbcType{VARCHAR}
     */
    public String getQrCode() {
        return qrCode;
    }

    public void setQrCode(String qrCode) {
        this.qrCode = qrCode;
    }

    /**
     * 描述  
     * column{Description},jdbcType{VARCHAR}
     */
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * 好友数  
     * column{Friends},jdbcType{INTEGER}
     */
    public Integer getFriends() {
        return friends;
    }

    public void setFriends(Integer friends) {
        this.friends = friends;
    }

    /**
     * 点赞数  
     * column{Praise},jdbcType{INTEGER}
     */
    public Integer getPraise() {
        return praise;
    }

    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * 待扩展信息  
     * column{Attributes},jdbcType{VARCHAR}
     */
    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}