package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_User_Feeds}
 * by is_zhoufeng@163.com 2015-06-07 14:53:51
 */
public class TUserFeeds implements Serializable {
    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    private Long id;

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    private Long userId;

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    private Date createTime;

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    private Date modifyTime;

    /**
     * 信息：json格式  
     * column{Attributes},jdbcType{VARCHAR}
     */
    private String attributes;

    /**
     *   
     * column{Like},jdbcType{INTEGER}
     */
    private Integer like;

    /**
     * 图片数  
     * column{PageCount},jdbcType{INTEGER}
     */
    private Integer pageCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_feeds
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{BIGINT}
     */
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户ID  
     * column{UserId},jdbcType{BIGINT}
     */
    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * 信息：json格式  
     * column{Attributes},jdbcType{VARCHAR}
     */
    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     *   
     * column{Like},jdbcType{INTEGER}
     */
    public Integer getLike() {
        return like;
    }

    public void setLike(Integer like) {
        this.like = like;
    }

    /**
     * 图片数  
     * column{PageCount},jdbcType{INTEGER}
     */
    public Integer getPageCount() {
        return pageCount;
    }

    public void setPageCount(Integer pageCount) {
        this.pageCount = pageCount;
    }
}