package com.zl.pojo;

import java.io.Serializable;
import java.util.Date;

/**
 * tableName{T_Version}
 * by is_zhoufeng@163.com 2015-06-06 22:21:31
 */
public class TVersion implements Serializable {
    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    private Integer id;

    /**
     * App编号  
     * column{AppId},jdbcType{INTEGER}
     */
    private Integer appId;

    /**
     * 应用名字  
     * column{AppnName},jdbcType{VARCHAR}
     */
    private String appnName;

    /**
     * 更新内容，换行用
  
     * column{Content},jdbcType{VARCHAR}
     */
    private String content;

    /**
     * 下载地址  
     * column{DownUrl},jdbcType{VARCHAR}
     */
    private String downUrl;

    /**
     * 最新版本号  
     * column{Version},jdbcType{VARCHAR}
     */
    private String version;

    /**
     * 扩展属性：Json格式保存App下载地址等  
     * column{Attributes},jdbcType{VARCHAR}
     */
    private String attributes;

    /**
     * 是否强制更新  
     * column{ForceUpdate},jdbcType{BIT}
     */
    private Boolean forceUpdate;

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    private Date createTime;

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     *   
     * column{Id},jdbcType{INTEGER}
     */
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * App编号  
     * column{AppId},jdbcType{INTEGER}
     */
    public Integer getAppId() {
        return appId;
    }

    public void setAppId(Integer appId) {
        this.appId = appId;
    }

    /**
     * 应用名字  
     * column{AppnName},jdbcType{VARCHAR}
     */
    public String getAppnName() {
        return appnName;
    }

    public void setAppnName(String appnName) {
        this.appnName = appnName;
    }

    /**
     * 更新内容，换行用
  
     * column{Content},jdbcType{VARCHAR}
     */
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    /**
     * 下载地址  
     * column{DownUrl},jdbcType{VARCHAR}
     */
    public String getDownUrl() {
        return downUrl;
    }

    public void setDownUrl(String downUrl) {
        this.downUrl = downUrl;
    }

    /**
     * 最新版本号  
     * column{Version},jdbcType{VARCHAR}
     */
    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * 扩展属性：Json格式保存App下载地址等  
     * column{Attributes},jdbcType{VARCHAR}
     */
    public String getAttributes() {
        return attributes;
    }

    public void setAttributes(String attributes) {
        this.attributes = attributes;
    }

    /**
     * 是否强制更新  
     * column{ForceUpdate},jdbcType{BIT}
     */
    public Boolean getForceUpdate() {
        return forceUpdate;
    }

    public void setForceUpdate(Boolean forceUpdate) {
        this.forceUpdate = forceUpdate;
    }

    /**
     *   
     * column{CreateTime},jdbcType{TIMESTAMP}
     */
    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *   
     * column{ModifyTime},jdbcType{TIMESTAMP}
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}