package com.zl.dao.mapper;

import com.zl.pojo.TBanner;
import com.zl.pojo.TBannerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBannerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int countByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insert(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insertSelective(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    List<TBanner> selectByExample(TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    TBanner selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TBanner record, @Param("example") TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExample(@Param("record") TBanner record, @Param("example") TBannerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKeySelective(TBanner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Banner
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKey(TBanner record);
}