package com.zl.dao.mapper;

import com.zl.pojo.TBrand;
import com.zl.pojo.TBrandExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TBrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int countByExample(TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByExample(TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insert(TBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insertSelective(TBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    List<TBrand> selectByExample(TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    TBrand selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TBrand record, @Param("example") TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExample(@Param("record") TBrand record, @Param("example") TBrandExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKeySelective(TBrand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Brand
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKey(TBrand record);
}