package com.zl.dao.mapper;

import com.zl.pojo.TChat;
import com.zl.pojo.TChatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TChatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int countByExample(TChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int deleteByExample(TChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int insert(TChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int insertSelective(TChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    List<TChat> selectByExample(TChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    TChat selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") TChat record, @Param("example") TChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int updateByExample(@Param("record") TChat record, @Param("example") TChatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int updateByPrimaryKeySelective(TChat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Chat
     *
     * @mbggenerated Tue Jun 09 17:21:21 CST 2015
     */
    int updateByPrimaryKey(TChat record);
}