package com.zl.dao.mapper;

import com.zl.pojo.TDeviceUser;
import com.zl.pojo.TDeviceUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TDeviceUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int countByExample(TDeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByExample(TDeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insert(TDeviceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insertSelective(TDeviceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    List<TDeviceUser> selectByExample(TDeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    TDeviceUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TDeviceUser record, @Param("example") TDeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExample(@Param("record") TDeviceUser record, @Param("example") TDeviceUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKeySelective(TDeviceUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Device_User
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKey(TDeviceUser record);
}