package com.zl.dao.mapper;

import com.zl.pojo.TFile;
import com.zl.pojo.TFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int countByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int deleteByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int insert(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int insertSelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    List<TFile> selectByExample(TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    TFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int updateByExampleSelective(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int updateByExample(@Param("record") TFile record, @Param("example") TFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int updateByPrimaryKeySelective(TFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_File
     *
     * @mbggenerated Tue Jun 09 16:41:24 CST 2015
     */
    int updateByPrimaryKey(TFile record);
}