package com.zl.dao.mapper;

import com.zl.pojo.TIndustryCategroy;
import com.zl.pojo.TIndustryCategroyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TIndustryCategroyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int countByExample(TIndustryCategroyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByExample(TIndustryCategroyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insert(TIndustryCategroy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insertSelective(TIndustryCategroy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    List<TIndustryCategroy> selectByExample(TIndustryCategroyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    TIndustryCategroy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TIndustryCategroy record, @Param("example") TIndustryCategroyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExample(@Param("record") TIndustryCategroy record, @Param("example") TIndustryCategroyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKeySelective(TIndustryCategroy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Industry_Categroy
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKey(TIndustryCategroy record);
}