package com.zl.dao.mapper;

import com.zl.pojo.TUserProfile;
import com.zl.pojo.TUserProfileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int countByExample(TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int deleteByExample(TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int insert(TUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int insertSelective(TUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    List<TUserProfile> selectByExample(TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    TUserProfile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") TUserProfile record, @Param("example") TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int updateByExample(@Param("record") TUserProfile record, @Param("example") TUserProfileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int updateByPrimaryKeySelective(TUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_profile
     *
     * @mbggenerated Sun Jun 07 14:53:51 CST 2015
     */
    int updateByPrimaryKey(TUserProfile record);
}