package com.zl.dao.mapper;

import com.zl.pojo.TUserInfo;
import com.zl.pojo.TUserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int countByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insert(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int insertSelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    List<TUserInfo> selectByExample(TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    TUserInfo selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExampleSelective(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByExample(@Param("record") TUserInfo record, @Param("example") TUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKeySelective(TUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_User_Info
     *
     * @mbggenerated Fri Jun 05 23:56:33 CST 2015
     */
    int updateByPrimaryKey(TUserInfo record);
}