package com.zl.dao.mapper;

import com.zl.pojo.TVersion;
import com.zl.pojo.TVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int countByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int deleteByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int insert(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int insertSelective(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    List<TVersion> selectByExample(TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    TVersion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int updateByExampleSelective(@Param("record") TVersion record, @Param("example") TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int updateByExample(@Param("record") TVersion record, @Param("example") TVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int updateByPrimaryKeySelective(TVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_Version
     *
     * @mbggenerated Sat Jun 06 22:21:31 CST 2015
     */
    int updateByPrimaryKey(TVersion record);
}